

Appendix A: Exodus summary
--------------------------


Appendix B: Exodus 15:1-21 by genre
-----------------------------------

> ^1^Then Moses and the Israelites sang this song to the Lord:
‘I will sing to the Lord,
    for he is highly exalted.
Both horse and driver
   he has hurled into the sea.
2 ‘The Lord is my strength and my defence;
    he has become my salvation.
He is my God, and I will praise him,
    my father’s God, and I will exalt him.
3 The Lord is a warrior;
    the Lord is his name.
4 Pharaoh’s chariots and his army
    he has hurled into the sea.
The best of Pharaoh’s officers
    are drowned in the Red Sea.
5 The deep waters have covered them;
    they sank to the depths like a stone.
6 Your right hand, Lord,
    was majestic in power.
Your right hand, Lord,
    shattered the enemy.
7 ‘In the greatness of your majesty
    you threw down those who opposed you.
You unleashed your burning anger;
    it consumed them like stubble.
8 By the blast of your nostrils the waters piled up.
The surging waters stood up like a wall;
    the deep waters congealed in the heart of the sea.
9 The enemy boasted,
    “I will pursue, I will overtake them.
I will divide the spoils;
    I will gorge myself on them.
I will draw my sword
    and my hand will destroy them.”
10 But you blew with your breath,
    and the sea covered them.
They sank like lead
    in the mighty waters.
11 Who among the gods
    is like you, Lord?
Who is like you –
     majestic in holiness,
awesome in glory,
    working wonders?


> ^12^‘You stretch out your right hand,
    and the earth swallows your enemies.
13 In your unfailing love you will lead
    the people you have redeemed.
In your strength you will guide them
     to your holy dwelling.
14 The nations will hear and tremble;
    anguish will grip the people of Philistia.
15 The chiefs of Edom will be terrified,
    the leaders of Moab will be seized with trembling,
the people of Canaan will melt away;
    16 terror and dread will fall on them.
By the power of your arm
    they will be as still as a stone –
until your people pass by, Lord,
    until the people you bought pass by.
You will bring them in and plant them
    on the mountain of your inheritance –
the place, Lord, you made for your dwelling,
    the sanctuary, Lord, your hands established.
18 ‘The Lord reigns for ever and ever.’
    19 When Pharaoh’s horses, chariots and horsemen went into the sea, the Lord brought the waters of the sea back over them, but the Israelites walked through the sea on dry ground. 20 Then Miriam the prophet, Aaron’s sister, took a tambourine in her hand, and all the women followed her, with tambourines and dancing.
21 Miriam sang to them:
‘Sing to the Lord,
    for he is highly exalted.
Both horse and driver
    he has hurled into the sea.’
Exodus 15:1‭-‬21 NIVUK


Appendix C Feedback Form
------------------------

TODO

Appendix D Presentation with notes
----------------------------------

TODO
