Rationale
=========

Background
----------

Church on the Green is a small church plant of Corsham Baptist Church comprising around forty people including children. Though small, it is quite well established with a tight-knit, committed congregation. There is a full range of ages, though under 14s have their own provision during the sermon. There is also a wide range of social backgrounds.

The church uses the New International Version (Anglicised), 2011 so quotations here are from that. I also refer to the English Standard Version and / or The Message as well during my preparation.

Reflection
----------

When first receiving a passage it is my practice to read the book it comes from completely twice. The first time I read quickly, ideally at one sitting, familiarising myself with the broad structure, key events, messages and order in which they appear. In one sense, this is particularly relevant to an Old Testament narrative such as Exodus. On the other hand, grasping messages intended, at least in the first instance, for a very different time, place and social milieu can be harder than for a gospel or epistle. While doing so, I like to create a visual summary, which I can then keep to hand for frequent reference (Included as Appendix A). I also consult the summary of several commentaries to see if they highlight other items.

My second reading is slower and focuses on the significant, challenging or other passages that the Holy Spirit has drawn my attention back to in the intervening time. I also start to look at my particular passage, since, in my case, it would be relatively unusual to have more than one passage to preach in a series. 

Now I am ready to consider the specific passage in detail. What struck me about this passage is genre. Just about all of the rest of Exodus is easily characterised as narrative, largely historical but history from the perspective of an God's growing revelation of Himself and the response of the people of Israel. Exodus 15, on the other hand, is a song of worship and celebration and is presented in verse. Even after translation we can see the poetic nature come through in couplets, each phrase of which is typically broken into two short phrases. Furthermore, one can see that each couplet may have been sung responsively (as is suggested by both Peter E. Enns[3] and R. Alan Cole[4]) , for example:

> ^2^The Lord is my strength and my defence;
    he has become my salvation.
He is my God, and I will praise him,
    my father's God, and I will exalt him.

Here we see the second part of the couplet responding to the first; a similar relationship exists between v5 & 6.

On other occasions the second part echos agreement or reinforces the first as in:

> ^3^The Lord is a warrior;
    the Lord is his name.

Verses 4 and 10 also take this form.
However, whilst the overall form is poetic there are further layers. One approach I sometimes use is to print and highlight different chunks to look for similarities and differences, and how ideas are developed. I've included this marked-up copy as Appendix B. 
In this case it revealed two halves to the song hinged on verse 13. The first half relates events and responds in praise for the way God, in his saving power, caused the events to happen. Praise of God's action in the past turns to confidence in his provision for the future.

It also suggested to me that this was a moment of realisation for the people of Israel when praise led them into wisdom. It brought to mind for me the passage in Mark 8:27-29 where the disciples have been with Jesus for some time, embracing his teaching, even stepping out in ministry themselves but the penny had not fully dropped, so to speak. The disciples clearly hoped Jesus was the Messiah but still needed prodding by Jesus to get up the confidence to actually say it out loud. Of course it is no surprise that Peter is the one to do so. In Exodus, the people of Israel clearly have a hope in the Lord but for the first time express the full picture that God's plan will redeem them and ultimately lead to dwelling with him in his holy place.

This acts as a springboard not just for praise and confidence in God's provision but prophesy about the victories he will supply in Canaan, the land promised to Abraham. Some commentators have suggested this forward looking section was a later addition citing in particular v13 and v17 ('holy dwelling') as references either to Mount Sinai or Solomon's temple and clearly the specifics of the encounters in the land of Canaan have not occurred yet. In defence, Cole notes these are archaic phrases with parallels in the Ras Shamra tablets as well as other old testament 'prophetic perfects' when the past tense described future events as having already happened[5]. Enns takes a slightly different view. While clearly stating he is not denying prophecy in the old testament, nor that the Israelites celebrated immediately after crossing the sea, he wants to consider that the 'canonical' version passed on to us may date from a later time. And that the biblical author saw no problem in that. Personally, I think Enns tries too hard to be fair to 'what the text will allow us to conclude'[6] and see Cole's argument for a theological use of the past tense as altogether simpler. However, I also decided there was little to be gained in exploring these hypotheses for the congregation. Instead I chose to emphasise, with J. Durham[7], that such a significant event would naturally be returned to frequently and even ritualised as liturgy, as for example, in Psalm 136.
The idea of focusing on unifying one message or theme from the text for the people gathered to hear it is a practice I have followed before but the suggestion of Paul Scott Wilson develops it further too. In this case, paraphrasing v13, I wrote: God's purpose for the Israelites, for me and for you, is to be redeemed in love and guided to his holy dwelling.

That's what God is doing but what are the people of God doing, then and now? Already in Exodus we have seen Israel lurch from a desire to follow God to disillusion and disobedience and we know this is a pattern that is repeated again and again in what follows. As Scott Wilson says, the ‘gospel is bad news before it is good news'. We have laid out for us here what it looks like to be an enemy of God. The I… I… I… of verse 9 is impossible to ignore. The consequences are equally clear.  Sadly, this is a message that resonates just as much today on ourselves and our society.
The need then of the congregation—and the preacher—is to be redeemed and for their memories to be fortified so that God's actions arising from unfailing love are not so quickly forgotten. Looking solely at this passage, the mission of the church is to support and remind one another of God's loving actions and to encourage one another to praise, as Miriam does.

The commentaries I consulted had interesting analysis of many other points of etymology such as the echo of Genesis 1:2 ‘the deep' in the v5 & 8 (‘deep waters') but ultimately these did not fit into this message.

Approach
--------

In order to take onboard the sense of praise and wonder of the first half of the passage I found reflecting on the circumstances and emotions of the particular situation helpful and decided to seek to lead the congregation in something similar with prompts and questions. Using pauses would be important to this approach.
Similarly, I have found my own spiritual life benefits from frequent little nudges. So I decided to share some of those, along with suggestions of what else might work for different types of people. 

Feedback
--------

Feedback suggested that the visual illustrations were appreciated but not too many so much as to become distracting. I also believe that the visualisation and placing oneself in the scene were helpful to the congregation from comments received afterwards (not the ‘official' feedback form).

On the other hand, I kicked myself for not asking someone to read the full passage. I can only say that I had mis-applied Rob's advice that some passages in this series stretch to several chapters and therefore not reading the full text should be considered. The other improvement suggested—to introduce the key idea at the start—surprised me a little more. I normally have clearly stated a summary at the outset, often in the form of a question and answer as suggested in Haddon Robinson's ‘Biblical Preaching' but this time I did not because the sermon seemed to have a development that matched the order of the passage.
