Sermon
======

Previously in Exodus…
---------------------

The people of Israel are riding high, God is moving in power just as he told Moses it would happen. Freedom from Pharaoh's enslavement has been granted, they were even given gifts by their recent oppressors as they left!
Today's passage is a real mix of styles, some of it is narrative, some praise and worship, some preaching or even prophetic. So I'm going to split them up and reveal the picture little by little. First the news report (vv1,4,5):


[quote]
____
[.pre-wrap]
^1^Then Moses and the Israelites sang this song to the Lord
^4^Pharaoh’s chariots and his army
  he has hurled into the sea.
The best of Pharaoh’s officers
     are drowned in the Red Sea.
^5^The deep waters have covered them;
     they sank to the depths like a stone.
____

Phew! But then the news is often dramatic, filled with pictures and stories from far away. Maybe we shrug and change channels?
But wait, put yourself in the place of the Israelites for a moment…
* Just weeks ago you were labouring to find straw for bricks, forming them and baking them under the hot Egyptian sun. And if you can’t picture baking under the sun today, just wait till tomorrow[1]. 

* There were plagues—again maybe that is easier to imagine than it might have been a few years ago.
* Pharoah released you to go with this fellow Moses. What did you think about that, or about him?
* And was your mind changing as he seemed to be wandering around in the desert, backtracking here and there?
* Pharaoh caught up to you, just yesterday. Were you ready to beg that he just spare your lives and lead you back to Egypt in chains? Were you ready to fight to the death?
Where was God in this?
* Moses said, that great cloud of fire and smoke is God. He’s been leading us. Certainly, it did move between us and the Egyptians yesterday; kept them off us!
* Moses certainly has the courage of his convictions: God will do the fighting and we were to just be still.
* He gathered us by the sea and held his staff out. Before you could say Jehovah Jireh—God will provide—we’re walking across the seabed, water on both sides. The first few streaks of morning light were creeping over the desert by the time the last families were stumbling hurriedly up the shore. We could already see the Egyptians gaining on us with their chariots.
* Then as quickly as it began it is over. What do you remember of it? How long was it before bodies started floating up to the shore?
Now what do you feel? Shocked? Tired? Adrenaline racing? Ecstatic?
What would you do next?

* Give thanks for your rescue?
* Praise God?
* Look to Rob [Senior pastor] or Adrian [Elder] to see what they are doing?

Let's take a look (vv1b-3)

> ^1b^ ‘I will sing to the Lord, for he is highly exalted. [ESV says I will sing to the lord for he has triumphed gloriously]
Both horse and driver he has hurled into the sea. 
^2^ ‘The Lord is my strength and my defence;
    he has become my salvation.
He is my God, and I will praise him,
    my father’s God, and I will exalt him.
^3^ The Lord is a warrior;
    the Lord is his name.

And vv11-12

> ^11^ Who among the gods
    is like you, Lord?
Who is like you –
     majestic in holiness,
awesome in glory,
    working wonders? 


> ^12^ ‘You stretch out your right hand,
    and the earth swallows your enemies.

First, recognition that God is worthy of praise. His actions make him worthy of praise. It was his actions that defeated the cream of the Egyptian army. And by his actions that we have been saved.

Then a confession of faith: this is my God and I will exalt him.

Finally, the rebuttal of the culture of many gods that Israel has grown up with. Remember they've been in Egypt for at least four generations and Egyptian culture was stuffed full of gods as anyone who's been to the British museum can tell you. Don’t think this is saying, ‘There are many gods, but I happen to believe in Yahweh because he's done a miracle with the waves’. This is simply God in his typically gentle way leading them out of the culture of Egypt at the same time he leads them out physically.

Before I move on let's pause a moment--in awe--to say with Moses "Who is like you – majestic in holiness, awesome in glory, working wonders?"

[Pause]

Now there's an issue here that you might find troubling so we need to tackle it. If it doesn't trouble you then just continue to meditate on the awesomeness of God for a moment.
Is Moses or indeed God celebrating or even enjoying the mass slaughter of Egyptians here? Is this a defence of nationalism or a justification of persecuting those who are not like us?
Just like occasions in the current war in Ukraine [see slide of Russian flagship Moskva sunk with most or all hands believed to be lost] I think it is quite understandable to celebrate being spared the suffering and death these weapons could have wrought without celebrating the suffering and death of enemies.
Verses 6 and 7 make it clear that God 'shatters the enemy' and 'overthrows [His] adversaries'. 

And who are these enemies? Verse 9 paints a picture of human arrogance: 'The enemy boasted, “I will pursue, I will overtake them. I will divide the spoils; I will gorge myself on them. I will draw my sword and my hand will destroy them.”' [my emphasis].
Far from endorsing any violence we may feel justified in, this is a warning. As Rob has preached already in this series, Exodus shows us God’s amazing grace but also what a terrible thing it is to be God’s enemy. 
That brings us conveniently to v13 where we see again the flip side of that argument. What purpose is God working out in this part of the history of his people?
In your unfailing love you will lead the people you have redeemed. In your strength you will guide them to your holy dwelling.
God's purpose for the Israelites, for me and for you, is to be redeemed in love and guided to his holy dwelling. As I was preparing this talk I kept being drawn back to this verse because to me this is when the penny drops, the light goes on and that longest journey from head to heart is completed. This is not a story about slaves, plagues, deserts or drowned enemies. It's not even a story about going to the mountain to worship God although those are all details along the way.
This is a story about God working out his plan to redeem his people, you and me, and lead us home.
That's got to be worth an amen or an hallelujah hasn't it!?
Verse 13 is also the pivotal verse in the song because we've reviewed the history and we've grasped its meaning in the present. Now we turn on to look at what it meant for the future of the Israelites back then and for the future of you and me when we leave here today.
The prophecy is contained in vv14-17:

> ^14^ The nations will hear and tremble;
    anguish will grip the people of Philistia.
^15^ The chiefs of Edom will be terrified,
    the leaders of Moab will be seized with trembling,
the people of Canaan will melt away;
    ^16^ terror and dread will fall on them.
By the power of your arm
    they will be as still as a stone –
until your people pass by, Lord,
    until the people you bought pass by.
You will bring them in and plant them
    on the mountain of your inheritance –
the place, Lord, you made for your dwelling,
    the sanctuary, Lord, your hands established.

I'm not going to get into whether this is contemporaneous with the crossing or a later addition. Opinions vary, but it seems clear that there is room for an initial and spontaneous response to this dramatic movement of God in power and also for such a crucial part of their redemption story to be repeated many times over the years.   
However, I do think that it is where the key lesson lies for later generations all the way down to ourselves. To unpack that I need to stray slightly into the following passage. V22:

> Then Moses led Israel from the Red Sea and they went into the Desert of Shur. For three days they travelled in the desert without finding water. 

Uh-oh! V23:

> When they came to Marah, they could not drink its water because it was bitter.

You know what’s coming next don’t you? V24:

> So the people grumbled against Moses, saying, ‘What are we to drink?’

THREE DAYS! THREE VERSES! That’s all it took to forget the most life changing and salvation affirming event of the century. Of several centuries! 

But before we get too critical of the Israelites let’s pause to examine our own hearts.
Who among us has not felt a bit hot and thirsty over the last week or so? What jumped into  your mind? Was it ‘Thank you God for the unfailing love that redeemed me and will yet guide me to your holy dwelling’? Or was it, ‘What am I to drink?’
Don’t feel too bad if you’re in the second camp, you’re not alone. There are many psychological studies on how we value what we already have less than what we may possibly gain. But what to do about it?

If you’ve heard me speak before you may know about the scraps of paper that I stick around the screen and walls of my office so they catch my eye often. This week I stuck up a new one: 

> ^13^ In your unfailing love you will lead
    the people you have redeemed.
In your strength you will guide them
    to your holy dwelling.

If you love music, play songs that preach to you God’s loving redemption. If you’re creative, draw or make beautiful reminders of his salvation. If you’re a reader, read of God’s gracious acts in the Bible or in the lives of his saints. If you’re a people person ask others in the church about their stories or share your own. If you’re a journaller, record the things you have received, in thanks to the LORD each day. Above all, remind yourself and your church family of your own unique story.
In conclusion, ‘throughout her history … Israel is constantly forgetting and needs to be reminded to keep her focus on the God who rules these circumstances, not on the circumstances themselves.’[2] We are no different, and that is the purpose of this song we’ve been reading today. 
It is no surprise that the reading ends where it began, though this time with Miriam leading the song. It is the people of God reminding themselves and each other of his actions and his redeeming love that will take us home.

> ^20^Then Miriam the prophet, Aaron’s sister, took a tambourine in her hand, and all the women followed her, with tambourines and dancing. ^21^Miriam sang to them:
‘Sing to the Lord,
for he is highly exalted.
Both horse and driver
he has hurled into the sea.’

